# Config file for Castlevania 64 NTSC 1.0 Recompilation.

[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
#rom_file_path = "cv64.decompressed.z64"
elf_path = "cv64.decompressed.us.elf"
#symbols_file_path = "CV64Syms/dump.toml"
relocatable_sections_path = "cv64.us.overlays.txt"
recomp_include = "#include \"cv64_recomp.h\""
bss_section_suffix = "_bss"

[patches]

ignored = [
    "func_80014EE0_15AE0", # handwritten, unused?
    "osVirtualToPhysical_recomp"
]

replaced = [
    "osVirtualToPhysical_recomp"
]

stubs = [

]

# When osAiGetLength returns a number that exceeds the target amount of samples per frame, the calculation (target samples per frame - osAiGetLength()) will result in a negative number.
# When the clamping takes place to prevent a number of bytes that is too small, it doesn't take into account the negative number that resulted from the calculation.
# Not doing this results in a negative number being given to osAiSetNextBuffer causing a massive memory leak and crash (because a signed negative number is being read as unsigned).
[[patches.instruction]]
func = "__amHandleFrameMsg"
vram = 0x8007945C
value = 0x00E3082A # sltu $at, $a3, $v1 -> slt $at, $a3, $v1
